#!/usr/bin/env python3
"""Generate memory/INDEX.md from the Summary of every memory file.

Spec: the index is always generated, never hand-written. The single source of truth
lives in each file's own Summary.
Usage: python3 memory/tools/gen_index.py
       python3 memory/tools/gen_index.py --check   compare only, do not write; exit 1 on mismatch
"""
import json, re, sys
from collections import defaultdict
from pathlib import Path

MEM = Path(__file__).resolve().parents[1]
ROOT = MEM.parents[0]


def fields(t):
    """The `## Memory Summary` fields as a dict. Accepts both ':' and '：' after labels."""
    m = re.search(r"^## Memory Summary[ \t]*$\n(.*?)(?=^## |\Z)", t, re.S | re.M)
    return dict(re.findall(r"^-\s*(\S.*?)\s*[:：]\s*(.+?)\s*$", m.group(1), re.M)) if m else {}


def build():
    """Build the full content of INDEX.md. Deterministic: the same input always yields
    the same string, so --check can compare it byte for byte with the file on disk."""
    usage = {}
    up = MEM / "3_procedural" / "usage.json"
    if up.exists():
        usage = json.loads(up.read_text(encoding="utf-8"))

    out = ["# INDEX — memory overview", "",
           "⚠️ **Generated by `tools/gen_index.py`. Do not edit by hand.**",
           "To change the content, edit each memory file's own `## Memory Summary`, then rerun.", ""]

    by_tag = defaultdict(list)

    # 2_semantic
    sem = sorted((MEM / "2_semantic").glob("*.md"))
    out += ["---", "", f"## 2_semantic ({len(sem)})", "",
            "| File | Tags | Brief | Updated |", "|---|---|---|---|"]
    for f in sem:
        d = fields(f.read_text(encoding="utf-8"))
        out.append(f"| `{f.name}` | {d.get('Tags','')} | {d.get('Brief','')} | {d.get('Updated','')} |")
        for t in re.split(r"[,，、]\s*", d.get("Tags", "")):
            if t.strip():
                by_tag[t.strip()].append(f"2_semantic/{f.name}")

    # 3_procedural
    proc = sorted(p for p in (MEM / "3_procedural").glob("*.md"))
    boot = [p for p in proc if fields(p.read_text(encoding="utf-8")).get("Access", "").strip() == "Boot"]
    trig = [p for p in proc if p not in boot]
    scope = {}
    for f in proc:
        b = fields(f.read_text(encoding="utf-8")).get("Scope", "").strip() or "(unset)"
        scope[b] = scope.get(b, 0) + 1
    tally = ", ".join(f"{k} {v}" for k, v in sorted(scope.items()))
    out += ["", "---", "", f"## 3_procedural ({len(proc)})", "",
            f"Scope: {tally}", "",
            "| File | Scope | Access | Times used | Brief |", "|---|---|---|---:|---|"]
    for f in boot + trig:
        d = fields(f.read_text(encoding="utf-8"))
        out.append(f"| `{f.name}` | {d.get('Scope','')} | {d.get('Access','')} "
                   f"| {usage.get(f.stem, 0)} | {d.get('Brief','')} |")

    # 1_episodic
    eps = sorted((MEM / "1_episodic").rglob("*.md"))
    todo = [e for e in eps if e.parent.name == "1_episodic"]
    out += ["", "---", "",
            f"## 1_episodic ({len(eps)}, {len(todo)} not yet consolidated)", "",
            "| File | Occurred | Brief |", "|---|---|---|"]
    for f in sorted(todo, key=lambda x: x.name):
        d = fields(f.read_text(encoding="utf-8"))
        out.append(f"| `{f.name}` | {d.get('Occurred','')} | {d.get('Brief','')} |")
    out += ["", f"`consolidated/` holds another {len(eps)-len(todo)} consolidated entries, "
            "sorted by the date in the file name."]

    # Tag index
    out += ["", "---", "", "## By tag", ""]
    for t in sorted(by_tag):
        out.append(f"- **`{t}`** ({len(by_tag[t])}): " + ", ".join(f"`{x}`" for x in sorted(by_tag[t])))

    return "\n".join(out) + "\n", (len(sem), len(proc), len(eps))


def main():
    want, (ns, np_, ne) = build()
    idx = MEM / "INDEX.md"

    if "--check" in sys.argv[1:]:
        got = idx.read_text(encoding="utf-8") if idx.exists() else None
        if got is None:
            print("INDEX.md does not exist; run gen_index.py")
            return 1
        if got == want:
            return 0
        # Point at the first mismatching line -- easier to chase than "differs".
        a, b = got.splitlines(), want.splitlines()
        for i in range(max(len(a), len(b))):
            x = a[i] if i < len(a) else "(no such line)"
            y = b[i] if i < len(b) else "(extra line)"
            if x != y:
                print(f"INDEX.md is stale: line {i+1} is \"{x}\", should be \"{y}\"; run gen_index.py")
                return 1
        return 1

    idx.write_text(want, encoding="utf-8")
    print(f"✅ memory/INDEX.md ({ns} semantic / {np_} procedural / {ne} episodic)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
