#!/usr/bin/env python3
"""Generate the dispatch table in CLAUDE.md from the Summary of 3_procedural/*.md.

Spec: CLAUDE.md holds no rule content, only pointers. The single source of truth for
the content is 3_procedural/. The `Brief` of each rule file is what actually gets read
at boot, so it is copied into the table.
Usage: python3 memory/tools/gen_dispatch.py
"""
import re, sys
from pathlib import Path

MEM = Path(__file__).resolve().parents[1]
ROOT = MEM.parents[0]
PROC = MEM / "3_procedural"
# Files whose dispatch table is rewritten. Only files that already contain MARK_A are
# touched; add more paths here if the agent has more than one CLAUDE.md.
TARGETS = [ROOT / "CLAUDE.md"]
MARK_A = "<!-- DISPATCH:START generated by gen_dispatch.py, do not edit by hand -->"
MARK_B = "<!-- DISPATCH:END -->"


def fields(text):
    """The `## Memory Summary` fields as a dict. Accepts both ':' and '：' after labels."""
    m = re.search(r"^## Memory Summary[ \t]*$\n(.*?)(?=^## |\Z)", text, re.S | re.M)
    return dict(re.findall(r"^-\s*(\S.*?)\s*[:：]\s*(.+?)\s*$", m.group(1), re.M)) if m else {}


def build():
    boot, trig = [], []
    for f in sorted(PROC.glob("*.md")):
        d = fields(f.read_text(encoding="utf-8"))
        row = (f.name, d.get("Brief", ""))
        (boot if d.get("Access", "").strip() == "Boot" else trig).append(row)
    out = [MARK_A, "",
           f"### Boot layer · always read at the start of every conversation ({len(boot)})", "",
           "| Rule | What it is |", "|---|---|"]
    out += [f"| `3_procedural/{n}` | {s} |" for n, s in boot]
    out += ["", f"### Triggered layer · read only when the condition holds ({len(trig)})", "",
            "| Rule | When to read |", "|---|---|"]
    out += [f"| `3_procedural/{n}` | {s} |" for n, s in trig]
    out += ["", MARK_B]
    return "\n".join(out)


def main():
    table = build()
    n = 0
    for p in TARGETS:
        if not p.exists():
            continue
        s = p.read_text(encoding="utf-8")
        if MARK_A not in s:
            continue
        s = re.sub(re.escape(MARK_A) + r".*?" + re.escape(MARK_B),
                   lambda _: table, s, flags=re.S)
        p.write_text(s, encoding="utf-8")
        n += 1
        print(f"✅ Dispatch table updated in {p.relative_to(ROOT)}")
    if not n:
        print(table)
    return 0


if __name__ == "__main__":
    sys.exit(main())
